services:

  app:
    build: .
    command: uv run fastapi dev --port 8000 --host 0.0.0.0
    ports:
      - 8000:8000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    restart: always


